version: "3"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 102199
      POSTGRES_DB: postgresDB

  app:
    image: app
    ports:
      - 3000:3000